import Vue from 'vue'

export const EventNames = {
  REFRESH_CLOUD: 'REFRESH_CLOUD',
  REFRESH_MAP: 'REFRESH_MAP',
  PLAYING: 'PLAYING',
  STOPPED: 'STOPPED',
  PLAY_VIDEO: 'PLAY_VIDEO',
  STOP_VIDEO: 'STOP_VIDEO',
  ATTACK_COUNT: 'ATTACK_COUNT',
  ATTACK_EVENT_COUNT: 'ATTACK_EVENT_COUNT',
  CLOUD_COUNT_WEB: 'CLOUD_COUNT_WEB',
  CLOUD_COUNT_MOBILE: 'CLOUD_COUNT_MOBILE',
  CLOUD_COUNT_DESKTOP: 'CLOUD_COUNT_DESKTOP',
  GOT_EVENT_DATA: 'GOT_EVENT_DATA',
  RESET_TIMELINE: 'RESET_TIMELINE',
  PLATFORM_VIEWS_TODAY: 'PLATFORM_VIEWS_TODAY'
}

export const EventState = {
  playing: false
}

export const Event = new Vue()
